services:
  roon-server:
    image: elgeeko/roon-server:latest
    container_name: lmgt-roon
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/Budapest
    volumes:
      - ${APP_DATA_DIR}/roon-server-bin:/opt/RoonServer
      - ${APP_DATA_DIR}/roon-cache:/var/roon
      - /home/umbrel/umbrel/home/Downloads/music:/music:ro
    user: "1000:1000"