version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: slskd
      APP_PORT: 5030
    container_name: slskd_app_proxy

  slskd:
    image: slskd/slskd:latest
    container_name: slskd
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    expose:
      - 5030
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
      - PUID=1000
      - PGID=1000
      - UMASK=0002
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data:/app
      - ${UMBREL_ROOT}/home/Downloads/incomplete:/app/incomplete
      - ${UMBREL_ROOT}/home/Downloads/complete:/app/downloads
      - ${UMBREL_ROOT}/home/Downloads/music:/music:ro
      - SLSKD_SHARED_DIR=/content/music
      - SLSKD_DOWNLOADS_DIR=/content/downloads
      - SLSKD_INCOMPLETE_DIR=/content/incomplete
      - SLSKD_CONFIG=/config
    restart: on-failure
  