version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: lmgt-soulseek
      APP_PORT: 5030
      PROXY_AUTH_ADD: "false"

  slskd:
    image: slskd/slskd:latest
    container_name: lmgt-soulseek
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    expose:
      - 5030
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
      - PUID=1000
      - PGID=1000
      - UMASK=0002
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data:/app
      - ${UMBREL_ROOT}/home/Downloads/incomplete:/content/incomplete
      - ${UMBREL_ROOT}/home/Downloads/complete:/content/downloads
      - ${UMBREL_ROOT}/home/Downloads/music:/content/music:ro
      - SLSKD_SHARED_DIR=/content/music
      - SLSKD_DOWNLOADS_DIR=/content/downloads
      - SLSKD_INCOMPLETE_DIR=/content/incomplete
      - SLSKD_CONFIG=/config
    restart: on-failure
    