services:
  app_proxy:
   environment:
     APP_HOST: ${APP_ID}_roon-now-playing_1
     APP_PORT: 3000

  roon-now-playing:
    image: ghcr.io/arthursoares/roon-now-playing:latest
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./cache:/app/cache
    environment:
      - PORT=3000