version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: lmgt-slskd_web_1
      APP_PORT: 5030
      PROXY_AUTH_ADD: 'false'
    container_name: lmgt-slskd_app_proxy_1
  web:
    image: slskd/slskd:latest
    restart: on-failure
    ports:
      - '5031:5031'
      - '50300:50300'
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
      - SLSKD_UMASK=0002
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data:/app
      - /home/umbrel/umbrel/home/Downloads/complete:/complete
      - /home/umbrel/umbrel/home/Downloads/incomplete:/incomplete
      - /home/umbrel/umbrel/home/Downloads/music:/music:ro
    container_name: lmgt-slskd_web_1
