version: '3.7'

services:
  tvheadend:
    image: lscr.io/linuxserver/tvheadend:latest
    container_name: lmgt-tvheadend
    restart: unless-stopped
<<<<<<< HEAD
    network_mode: host         
=======
    ports:
      - "9981:9981"
      - "9982:9982"
>>>>>>> main
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/recordings:/recordings
