version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: lmgt-torrserver_app_1
      APP_PORT: 5665
      PROXY_AUTH_ADD: 'false'
    container_name: lmgt-torrserver_app_proxy_1
  app:
    image: ghcr.io/yourok/torrserver:latest
    environment:
      TS_PORT: '5665'
      TS_DONTKILL: '1'
      TS_HTTPAUTH: '0'
      TS_CONF_PATH: /opt/ts/config
      TS_TORR_DIR: /opt/ts/torrents
    volumes:
      - ${APP_DATA_DIR}/data/torrents:/opt/ts/torrents
      - ${APP_DATA_DIR}/data/config:/opt/ts/config
    container_name: lmgt-torrserver_app_1
